from configs.core import DEFAULT_SEED
from configs.models import DEFAULT_EMBEDDER, DEFAULT_LLM
from configs.prompts import PROMPTS

DEFAULT_AGENT_PARAMETERS = {
    "seed": DEFAULT_SEED,
    # "response_format": {"type": "text"},
    "response_format": {"type": "json_object"},
    "temperature": 0,
    "top_p": 1.0,
    "max_tokens": 4096,  # 2048
    "max_retries": 2,
    "timeout": 60,
}


AGENTS = {
    "default": {
        "priority": 0,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_system": PROMPTS["default"]["prompt_system"],
        "prompt_params": PROMPTS["default"]["prompt_params"],
        "prompt_template": PROMPTS["default"]["prompt_template"],
        "response_template": PROMPTS["default"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "embedder": {
        "priority": 0,
        "needs_review": False,
        "model": {
            "type": "embedder",
            "api": DEFAULT_EMBEDDER["api"],
            "size": DEFAULT_EMBEDDER["size"],
        },
        "prompt_params": PROMPTS["default"]["prompt_params"],
        "prompt_template": PROMPTS["default"]["prompt_template"],
        "response_template": PROMPTS["default"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "responder": {
        "priority": 1,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["responder"]["prompt_params"],
        "prompt_template": PROMPTS["responder"]["prompt_template"],
        "response_template": PROMPTS["responder"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "goal_engineer": {
        "priority": 1,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["goal_engineer"]["prompt_params"],
        "prompt_template": PROMPTS["goal_engineer"]["prompt_template"],
        "response_template": PROMPTS["goal_engineer"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "director": {
        "priority": 0,
        "needs_review": False,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["director"]["prompt_params"],
        "prompt_template": PROMPTS["director"]["prompt_template"],
        "response_template": PROMPTS["director"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "team_reporter": {
        "priority": 1,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["team_reporter"]["prompt_params"],
        "prompt_template": PROMPTS["team_reporter"]["prompt_template"],
        "response_template": PROMPTS["team_reporter"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "project_reporter": {
        "priority": 1,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["project_reporter"]["prompt_params"],
        "prompt_template": PROMPTS["project_reporter"]["prompt_template"],
        "response_template": PROMPTS["project_reporter"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "project_manager": {
        "priority": 0,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["project_manager"]["prompt_params"],
        "prompt_template": PROMPTS["project_manager"]["prompt_template"],
        "response_template": PROMPTS["project_manager"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "task_manager": {
        "priority": 1,
        "needs_review": False,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["task_manager"]["prompt_params"],
        "prompt_template": PROMPTS["task_manager"]["prompt_template"],
        "response_template": PROMPTS["task_manager"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "task_decomposer": {
        "priority": 1,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["task_decomposer"]["prompt_params"],
        "prompt_template": PROMPTS["task_decomposer"]["prompt_template"],
        "response_template": PROMPTS["task_decomposer"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "prompt_engineer": {
        "priority": 1,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["prompt_engineer"]["prompt_params"],
        "prompt_template": PROMPTS["prompt_engineer"]["prompt_template"],
        "response_template": PROMPTS["prompt_engineer"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    # "planner": {
    #     "priority": 1,
    #     "needs_review": True,
    #     "model": {
    #         "type": "llm",
    #         "api": DEFAULT_LLM["api"],
    #         "size": DEFAULT_LLM["size"],
    #     },
    #     "prompt_params": PROMPTS["planner"]["prompt_params"],
    #     "prompt_template": PROMPTS["planner"]["prompt_template"],
    #     "response_template": PROMPTS["planner"]["response_template"],
    #     "tools": [],
    #     "parameters": DEFAULT_AGENT_PARAMETERS,
    # },
    "source_selector": {
        "priority": 1,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["user_proxy"]["prompt_params"],
        "prompt_template": PROMPTS["user_proxy"]["prompt_template"],
        "response_template": PROMPTS["user_proxy"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "researcher": {
        "priority": 1,
        "needs_review": True,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["researcher"]["prompt_params"],
        "prompt_template": PROMPTS["researcher"]["prompt_template"],
        "response_template": PROMPTS["researcher"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "reviewer": {
        "priority": 1,
        "needs_review": False,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["reviewer"]["prompt_params"],
        "prompt_template": PROMPTS["reviewer"]["prompt_template"],
        "response_template": PROMPTS["reviewer"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "user_proxy": {
        "priority": 0,
        "needs_review": False,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["user_proxy"]["prompt_params"],
        "prompt_template": PROMPTS["user_proxy"]["prompt_template"],
        "response_template": PROMPTS["user_proxy"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
    "developer": {
        "priority": 1,
        "needs_review": False,
        "model": {
            "type": "llm",
            "api": DEFAULT_LLM["api"],
            "size": DEFAULT_LLM["size"],
        },
        "prompt_params": PROMPTS["developer"]["prompt_params"],
        "prompt_template": PROMPTS["developer"]["prompt_template"],
        "response_template": PROMPTS["developer"]["response_template"],
        "tools": [],
        "parameters": DEFAULT_AGENT_PARAMETERS,
    },
}
